name: push_gitee

on:
  workflow_dispatch:  # 支持手动触发工作流

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
    - name: 检出仓库
      uses: actions/checkout@v4
      with:
        ref: GUI-Live  # 确保检出的是 GUI-Live 分支

    - name: 设置Git配置文件
      run: |
        git config --global user.name '小朱'
        git config --global user.email '10714957+xiao-zhu245@user.noreply.gitee.com'

    - name: 向Gitee同步仓库
      env:
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      run: |
        git remote add gitee https://xiao-zhu245:${{ secrets.GITEE_TOKEN }}@gitee.com/xiao-zhu245/SkyAutoMusic.git
        git fetch gitee
        git reset --soft gitee/GUI-Live  # 软重置保持工作区不变
        git commit -m "从GitHub-CI同步过来的文件" || echo "No changes to commit"
        git push --force gitee GUI-Live  # 强制推送到远程仓库
